### ISSUE TITLE
issue with extra_hosts in docker-compose in development

### ISSUE THREAD

**Issue by benharosh** [balena-io-modules/resin-compose-parse#44]
Hi, we are experiencing a similar issue to [#661 on balena-supervisor](https://github.com/balena-io/balena-supervisor/issues/661) in development. Looks like the problem is with the parsing of the IP address. 

Running with OS Version `Resin OS 2.15.1+rev2` and Supervisor version `7.16.6`

docker-compose.yml without using environment variables:
```
version: '2'
  
services:
  artifactory-go-cli:
    build:
      context: ./go-cli
      dockerfile: Dockerfile
    hostname: artifactory-go-cli
    network_mode: "host"
    extra_hosts:
      - bebop:192.168.1.223


  bebop:
    build:
      context: ./bebop
      dockerfile: Dockerfile
    hostname: bebop
    network_mode: "host"
    extra_hosts:
      - go.cli:192.168.1.223
    ports:
    - 8080:8080/tcp
```

and the error that we are getting on balena when running `balena logs -f resin_supervisor` is:

```
[2018-11-06T06:46:39.904Z] Apply error Error: (HTTP code 400) unexpected - invalid IP address in add-host: "192.168.1.223:0"
[2018-11-06T06:46:39.910Z] Event: Service install error {"error":{"message":"(HTTP code 400) unexpected - invalid IP address in add-host: \"192.168.1.223:0\" ","stack":"Error: (HTTP code 400) unexpected - invalid IP address in add-host: \"192.168.1.223:0\" \n    
  at /usr/src/app/dist/app.js:638:87671\n    
  at /usr/src/app/dist/app.js:638:87634\n    
  at m.buildPayload (/usr/src/app/dist/app.js:638:87644)\n    
  at IncomingMessage.<anonymous> (/usr/src/app/dist/app.js:638:87144)\n    
  at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    
  at endReadableNT (_stream_readable.js:974:12)\n    
  at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    
  at process._tickCallback (internal/process/next_tick.js:104:9)"},"service":{"appId":1284993,"serviceId":121529,"serviceName":"artifactory-go-cli","releaseId":658053,"image":"sha256:cfa59e12feac1f79866dfa6e3a5c466bebbb7d1cd0054a64ee07c1547571dc07","labels":{"io.resin.architecture":"armv7hf","io.resin.device-type":"raspberry-pi2","io.resin.qemu.version":"3.0.0+resin-arm","io.resin.supervised":"true","io.resin.app-id":"1284993","io.resin.service-id":"121529","io.resin.service-name":"artifactory-go-cli"}}}
```

We also received an error when trying to work with docker-config environment variables and it seems that the parser wasn't able to resolve it. For example, when trying to use the ip address environment variable `BEBOP_IP_ADD=192.168.1.223` that is defined at the .env config file, and then trying to use this variable as the value of the extra_hosts field at docker-compose.yml `extra_hosts:  - "bebop:${BEBOP_IP_ADD}"`, we would receive a parsing error which is described down.

docker-compose.yml when using environment variables:

```
version: '2'
  
services:
  artifactory-go-cli:
    build:
      context: ./go-cli
      dockerfile: Dockerfile
    hostname: go-cli
    network_mode: "host"
    extra_hosts:
      - "bebop:${BEBOP_IP_ADD}"


  bebop:
    build:
      context: ./bebop
      dockerfile: Dockerfile
    hostname: bebop
    network_mode: "host"
    extra_hosts:
      - "go.cli:${GOCLI_IP_ADD}"
    ports:
    - 8080:8080/tcp
    - 8081:8081/tcp
    - 3000:3000/tcp
```

with `.env` file :
```
GOCLI_IP_ADD=192.168.1.223
BEBOP_IP_ADD=192.168.1.223
```
when running
`$ docker-compose config`

against the above docker-compose.yml file, it was able to resolve the environment variables without errors or warnings. However when pushing the code to balena we are receiving the below error when running `balena logs -f resin_supervisor`:
```
[2018-11-06T07:46:49.142Z] Scheduling another update attempt due to failure:  30000 { Error: (HTTP code 400) unexpected - invalid IP address in add-host: "${GOCLI_IP_ADD}:0"
    at /usr/src/app/dist/app.js:638:87671
    at /usr/src/app/dist/app.js:638:87634
    at m.buildPayload (/usr/src/app/dist/app.js:638:87644)
    at IncomingMessage.<anonymous> (/usr/src/app/dist/app.js:638:87144)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  reason: undefined,
  statusCode: 400,
  json: { message: 'invalid IP address in add-host: "${GOCLI_IP_ADD}:0"' } }
[2018-11-06T07:46:49.150Z] Apply error Error: (HTTP code 400) unexpected - invalid IP address in add-host: "${GOCLI_IP_ADD}:0"
```
 
We'd appreciate if you can look into this one.
Cheers

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_i7ob)
